# Generated by Django 4.2.20 on 2026-06-10 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('slug', models.SlugField()),
                ('tipo', models.CharField(choices=[('credito', 'Crédito'), ('debito', 'Débito'), ('efectivo', 'Efectivo')], max_length=10, verbose_name='tipo')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='balance')),
                ('emisor', models.CharField(blank=True, max_length=100, verbose_name='emisor')),
                ('ultimos_digitos', models.CharField(blank=True, max_length=4, verbose_name='últimos 4 dígitos')),
                ('dia_corte', models.CharField(blank=True, max_length=20, verbose_name='día de corte')),
                ('dia_pago', models.CharField(blank=True, max_length=20, verbose_name='día de pago')),
                ('vencimiento', models.CharField(blank=True, max_length=10, verbose_name='vencimiento')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.color', verbose_name='color')),
                ('icono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.icono', verbose_name='icono')),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tenant', verbose_name='inquilino')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'unique_together': {('inquilino', 'slug')},
            },
        ),
    ]
