# Generated by Django 4.2.20 on 2026-06-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
