# Generated by Django 4.2.20 on 2026-06-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_cuenta_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='límite de crédito'),
        ),
    ]
