# Generated by Django 4.2.20 on 2026-06-11 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurrenciaTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto')),
                ('periodicidad', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], max_length=10, verbose_name='periodicidad')),
                ('dia', models.IntegerField(default=1, help_text='Día del mes (1-31) o día de semana (0=lun, 6=dom)', verbose_name='día')),
                ('proxima_ejecucion', models.DateField(verbose_name='próxima ejecución')),
                ('nota', models.TextField(blank=True, verbose_name='nota')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrencias_destino', to='accounts.cuenta', verbose_name='cuenta destino')),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tenant', verbose_name='inquilino')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrencias_origen', to='accounts.cuenta', verbose_name='cuenta origen')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Recurrencia de Transferencia',
                'verbose_name_plural': 'Recurrencias de Transferencias',
                'ordering': ['proxima_ejecucion'],
            },
        ),
    ]
