# Generated by Django 4.2.30 on 2026-06-23 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('transfers', '0002_recurrenciatransferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrenciatransferencia',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurrencias_destino', to='accounts.cuenta', verbose_name='cuenta destino'),
        ),
        migrations.AlterField(
            model_name='recurrenciatransferencia',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurrencias_origen', to='accounts.cuenta', verbose_name='cuenta origen'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_destino', to='accounts.cuenta', verbose_name='cuenta destino'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_origen', to='accounts.cuenta', verbose_name='cuenta origen'),
        ),
    ]
