# Generated by Django 4.2.20 on 2026-06-23 21:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0003_alter_recurrenciatransferencia_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrenciatransferencia',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='recurrenciatransferencia',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='monto'),
        ),
        migrations.AlterField(
            model_name='recurrenciatransferencia',
            name='proxima_ejecucion',
            field=models.DateField(db_index=True, verbose_name='próxima ejecución'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='monto'),
        ),
    ]
