# Generated by Django 4.2.30 on 2026-06-23 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0002_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.cuenta', verbose_name='método de pago'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.cuenta', verbose_name='cuenta'),
        ),
    ]
