# Generated by Django 4.2.20 on 2026-06-11 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theme', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAhorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('slug', models.SlugField()),
                ('meta', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='meta')),
                ('monto_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='monto actual')),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='fecha límite')),
                ('nota', models.TextField(blank=True, verbose_name='nota')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.color', verbose_name='color')),
                ('icono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.icono', verbose_name='icono')),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tenant', verbose_name='inquilino')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Meta de Ahorro',
                'verbose_name_plural': 'Metas de Ahorro',
                'ordering': ['-creado'],
                'unique_together': {('inquilino', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='DepositoAhorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('nota', models.TextField(blank=True, verbose_name='nota')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tenant', verbose_name='inquilino')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depositos', to='savings.metaahorro', verbose_name='meta de ahorro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Depósito',
                'verbose_name_plural': 'Depósitos',
                'ordering': ['-fecha', '-creado'],
            },
        ),
    ]
