# Generated by Django 4.2.30 on 2026-06-23 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_depositoahorro_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositoahorro',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depositos', to='savings.metaahorro', verbose_name='meta de ahorro'),
        ),
    ]
