# Generated by Django 4.2.20 on 2026-06-23 21:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_alter_depositoahorro_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositoahorro',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='monto'),
        ),
        migrations.AlterField(
            model_name='metaahorro',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='metaahorro',
            name='meta',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='meta'),
        ),
    ]
