# Generated by Django 4.2.20 on 2026-06-23 21:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_alter_presupuesto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='monto_limite',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='límite mensual'),
        ),
    ]
